default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://postgres:postgres@localhost/cohortful_development

test:
  <<: *default
  database: cohortful_test

production:
  <<: *default
  database: cohortful_production
